services:
  api:
    build:
      context: .
      dockerfile: .docker/php-api/Dockerfile
    ports:
      - "8081:80" #maps port 8081 on host to port 80 in the container
    volumes:
      - ./api:/var/www/html
  app:
    build:
      context: .
      dockerfile: .docker/vue-app/Dockerfile
    container_name: vue-app
    ports:
      - "8080:8080"
  db:
    image: mariadb:latest
    container_name: mariadb-compose
    environment:
      MYSQL_DATABASE: mappers_db
      MYSQL_USER: mappers_dbuser
      MYSQL_PASSWORD: Ch4ngeM3
      MYSQL_ROOT_PASSWORD: Ch4ngeM32,plz.
    ports:
      - "3306:3306"
